M48
; DRILL file {KiCad (6.0.10)} date Thu Feb 16 14:31:00 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-16T14:31:00-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0598
%
G90
G05
T1
X4.7Y-2.4
X5.3Y-2.0
X5.4Y-2.3
X5.4Y-2.5
X5.5Y-2.5
X5.5898Y-2.1102
X5.9Y-2.4
X6.0Y-2.4
T2
X5.3Y-1.2
X5.5Y-1.2
T0
M30
